# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbtopocor',
                'doc_host': 'https://swalterfub.github.io',
                'git_url': 'https://github.com/swalterfub/nbtopocor',
                'lib_path': 'nbtopocor'},
  'syms': {'nbtopocor.core': {'nbtopocor.core.foo': ('core.html#foo', 'nbtopocor/core.py')}}}
